spring:
  application:
    name: pro_sotrudnikov
  datasource:
    url: jdbc:mysql://localhost:3306/pro_sotrudnikov
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1958-Sveta
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml